### ISSUE TITLE
Feature: Built in auth

### ISSUE THREAD

**Issue by nehero** [adonisjs/adonis-app#13]
Did you have any plan to implement an auth system with the starter adonis project?

I've started work on one based on Laravel's. 

Not sure if you want to keep this issue open for awhile for people to see so they can help contribute.

The branch is over on my repo at 

https://github.com/nehero/adonis-app/tree/feature-auth

I really want to see this framework grow :

Edit: If you have no intentions of adding an auth service to the default project, feel free to close this

**Comment by thetutlage** [comment]
Yes upcoming release will have inbuilt authentication system, here is an issue already open for same

https://github.com/adonisjs/adonis-auth/issues/1 and here is the roadmap of adonis

https://trello.com/c/wns5DzT3/28-authentication-provider

**Comment by nehero** [comment]
My bad, should have looked a bit harder
