### ISSUE TITLE
Restore Project

### ISSUE THREAD

**Issue by domdeger** [adonisjs/adonis-app#4]
Hello,

I have a problem. I've created an app using adonisjs on my notebook. After finishing my business trip i checked in the source code to my git repository. I checked out the code from my workstation but im not able to run the app again.

I checked out the code, ran an "npm install" and edited the .env file accordingly. But when i ran"npm start" 
the output is "info: serving app on port undefined"...

The strange thing was, that a new adonis project would start like a charm on my system.
The problem was that the "bootstrap" folder was outdated in my git version. So i would suggest to make the bootstrap part an own module?

I hope i could help a bit ;)

**Comment by thetutlage** [comment]
Yes, can you show me `boostrap/http.js` file

**Comment by domdeger** [comment]
Ofcourse

http.js:

**Comment by domdeger** [comment]
'use strict'

/*
|--------------------------------------------------------------------------
|   Bootstrap App
|--------------------------------------------------------------------------
|
|  Here we bootsrap our http server by registering providers to IOC
|  container , and autoloading app directory
|
*/

const fold = require('adonis-fold')
const app = require('./app')
const path = require('path')
const Registerar = fold.Registerar
const packageFile = require('../package.json')
const Ioc = fold.Ioc

module.exports = function(){

  Registerar
  .register(app.providers,app.deferredProviders)
  .then(function(){

    /*
    |--------------------------------------------------------------------------
    |   Setting Up aliases
    |--------------------------------------------------------------------------
    |
    |   After registering providers with Ioc container , we define registered
    |   aliases for them.
    |
    */
    Ioc.aliases(app.aliases)

    /*
    |--------------------------------------------------------------------------
    |   App Helpers
    |--------------------------------------------------------------------------
    |
    |   Here we setup app helpers, helpers gives absolute path to certain
    |   directories , which is indeed required by core and other
    |   service providers
    |
    */
    const Helpers = use("Helpers")
    Helpers.load(path.join(__dirname,'../package.json'))

    /*
    |--------------------------------------------------------------------------
    |   App namespace
    |--------------------------------------------------------------------------
    |
    |   Here we bind app directory as autoload path with Ioc container
    |
    */
    const Namespace = use("Namespace")
    Namespace.autoload()

    /*
    |--------------------------------------------------------------------------
    |   Loading Middlewares
    |--------------------------------------------------------------------------
    |
    |   Here we register http middlewares
    |
    */
    use("App/Http/kernel")

    /*
    |--------------------------------------------------------------------------
    |   Loading Routes
    |--------------------------------------------------------------------------
    |
    |   Here we register routes to http dispatcher.
    |
    */
    use("App/Http/routes")


    /*
    |--------------------------------------------------------------------------
    |   Application Exceptions
    |--------------------------------------------------------------------------
    |
    |   Here we make sure we are handling any exceptions thrown during
    |   http request.
    |
    */
    use("App/Exceptions/handler")

    /*
    |--------------------------------------------------------------------------
    |   Setting up static resource
    |--------------------------------------------------------------------------
    |
    |   Here we setup static directory to server static assets
    |
    */
    const Static = use("Static")
    Static.public('public',path.join(__dirname,'../public'))

    /*
    |--------------------------------------------------------------------------
    |   Starting server
    |--------------------------------------------------------------------------
    |
    |   As everything is loaded and configured properly , we can start
    |   our server on a given port.
    |
    */
    const Server = use("Server")
    const Env = use("Env")
    Server.start(Env.get("APP_PORT"))

  }).catch(function(error){
    console.log(error.stack);
    process.exit(0)
  })

}

**Comment by thetutlage** [comment]
Replace 

```javascript
Server.start(Env.get("APP_PORT"))
```

with

```javascript
Server.start(Env.get("APP_HOST"), Env.get("APP_PORT"))
```

Also add `APP_HOST` to your .env file

```
APP_HOST=0.0.0.0
```

**Comment by domdeger** [comment]
Thank you for your help ;)
