### ISSUE TITLE
Stick with lowercase

### ISSUE THREAD

**Issue by NicolasParada** [adonisjs/adonis-app#5]
[Stick with lowercase](https://blog.heroku.com/archives/2015/11/10/node-habits-2016#4-stick-with-lowercase)

>Some languages encourage filenames that match class names, like `MyClass` and 'MyClass.js'. Don't do that in node. Instead, use lowercase files:
>```
>let MyClass = require('my-class');
>```
>Node.js is the rare example of a Linux-centric tool with great cross-platform support. While OSX and Windows will treat 'myclass.js' and 'MyClass.js' equivalently, Linux won't. To write code that's portable between platforms, you'll need to exactly match `require` statements, *including capitalization*.
>
>The easy way to get this right is to just stick with lowercase filenames for everything, eg 'my-class.js'.

**Comment by RomainLanz** [comment]
We can close this, stick with capitalization is not a problem.

Thanks for your advice @NicolasParada, but has it said:

> *The easy way* to get this right is to just stick with lowercase filenames for everything, eg 'my-class.js'.

**Comment by thetutlage** [comment]
@NicolasParada Some how this issue got ignored. The basic point is to stick to a single file name convention, whether it is Capitalize or Lowercase. 

I choose Capitalize. :)
