### ISSUE TITLE
Include simple ORM sample

### ISSUE THREAD

**Issue by AndrewGaspar** [adonisjs/adonis-app#6]
I'm trying to use the documentation at adonisjs.com to figure out how to create Lucid models in a SQLite database, but it would be much easier if this sample app had an example of, say, a simple one to many relationship model.

**Comment by thetutlage** [comment]
It is there already http://adonisjs.com/docs/2.0/lucid-relations#relationships

**Comment by AndrewGaspar** [comment]
I'm asking for a sample in the context of this specific "hello world" app.

Also, one of the things that frustrated me about the docs on this specific case is that I got the sense that the Sqlite table would automatically be created for me, but it turns out you have to create it manually with the shape of the ORM object via a DB migration. This is fine, but it just wasn't clear from the docs that you need to do this, so those could stand to be updated, too.

Also, there should be a built-in method on table for specifying that a table should support soft deletes so I don't have to manually call `table.timestamp('deleted_at')`. Something like `table.softDeletes()`. The precedent for this is the `table.timestamps()` method that adds 'created_at' and 'updated_at'.

**Comment by thetutlage** [comment]
Agree with soft deletes method in schema creation, will add that.

If you find missing bits in the documentation, than i would appreciate if you can send a pull request with updated docs

I just released 2.0 couple of days back, so need time to gather content and examples apps for community
